# Stage --> Job --> Step

trigger:
- master

pool:
  vmImage: ubuntu-latest


stages:
- stage: stageA
  jobs:
  - job: jobA
    steps:
    - bash: echo stepA

- stage: stageB
  dependsOn: stageA
  jobs:
  - job: jobB
    steps:
    - bash: echo stepB

- stage: stageC
  dependsOn: stageA
  jobs:
  - job: jobC
    steps:
    - bash: echo stepC

- stage: stageD
  dependsOn:
  - stageB
  - stageC
  jobs:
  - job: jobD
    steps:
    - bash: echo stepD