# Stage --> Job --> Step

trigger:
- master

pool:
  vmImage: ubuntu-latest


stages:
- stage: stageA
  jobs:
  - job: jobA
    steps:
    - step: echo stepA

- stage: stageB
  jobs:
  - job: jobB
    steps:
    - step: echo stepB

- stage: stageC
  jobs:
  - job: jobC
    steps:
    - step: echo stepC
