
trigger:
- master

# strategy:
#   matrix:
#     linux:
#       operatingSystem: ubuntu-latest
#     mac:
#       operatingSystem: macos-latest
pool:
  vmImage: ubuntu-latest



stages:
- stage: BuildDev
  jobs:
  - job: BuildDev
    steps:
    - bash: echo BuildDev

- stage: DeployDev
  jobs:
  - deployment: DeployDev
    environment: DEV
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo DeployDev

- stage: DeployQA
  jobs:
  - deployment: DeployQA
    environment: QA
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo DeployQA